train: C:/Users/Nut/Chula/Year4Sem2/comp-vision/computer-vision-final-project/basketball.v74i.yolov8/train
val: C:/Users/Nut/Chula/Year4Sem2/comp-vision/computer-vision-final-project/basketball.v74i.yolov8/valid
test: C:/Users/Nut/Chula/Year4Sem2/comp-vision/computer-vision-final-project/basketball.v74i.yolov8/test

# replace '...' with your local absolute paths
# download the dataset used here: https://universe.roboflow.com/034-ganesh-kumar-m-v-cs-r2lwe/basketball-lhqoe/dataset/1

# nc: 2
# names: ['Basketball', 'Basketball Hoop']

nc: 3
names: ['ball', 'basket', 'goal']
