train: /Users/sorawitthanitthapongsa/Desktop/Year4/SS/Comp-vision/project/final_project/computer-vision-final-project/basketball.v74i.yolov8/train
val: /Users/sorawitthanitthapongsa/Desktop/Year4/SS/Comp-vision/project/final_project/computer-vision-final-project/basketball.v74i.yolov8/valid
test: /Users/sorawitthanitthapongsa/Desktop/Year4/SS/Comp-vision/project/final_project/computer-vision-final-project/basketball.v74i.yolov8/test

# replace '...' with your local absolute paths
# download the dataset used here: https://universe.roboflow.com/034-ganesh-kumar-m-v-cs-r2lwe/basketball-lhqoe/dataset/1

# nc: 2
# names: ['Basketball', 'Basketball Hoop']

nc: 3
names: ['ball', 'basket', 'goal']
