train: /Users/natananph/Documents/Chula/Year4Sem2/comp-vision/AI-Basketball-Shot-Detection-Tracker-master/dataset/train
val: /Users/natananph/Documents/Chula/Year4Sem2/comp-vision/AI-Basketball-Shot-Detection-Tracker-master/dataset/valid
test: /Users/natananph/Documents/Chula/Year4Sem2/comp-vision/AI-Basketball-Shot-Detection-Tracker-master/dataset/test

# replace '...' with your local absolute paths
# download the dataset used here: https://universe.roboflow.com/034-ganesh-kumar-m-v-cs-r2lwe/basketball-lhqoe/dataset/1

nc: 2
names: ['Basketball', 'Basketball Hoop']
